#baseURL = "https://happy-hugle-8dfa0b.netlify.app"
baseURL = "https://th3lastgam3.com"

languageCode = "en-us"
title = "The Last Game"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "FIRST CO-LOCATED GAME BASED ON NFTS"

[Author]
    name = "th3lastgam3"
    email = "the.last.game.contest@gmail.com"

[Social]
    twitter = "Th3LastGam3"
